config/routes.rb
Rails.application.routes.draw do

  get 'client_works/new'

  get 'client_works/create'

  get 'client_works/edit'

  get 'client_works/update'

  get 'client_works/delete'

  get 'client_works/show'

  get 'client_works/index'

   root 'users#index'

  devise_for :users

  resources :users ,only: [:index, :show]

  resources :users ,only: [:new, :create] do
    resources :user_works ,only: [:new, :create,:destroy, :edit]
  end


   resources :users ,only: [:new, :create] do
    resources :daily_reports ,only: [:new, :create,:destroy, :edit]
  end

    resources :clients ,only: [:new, :create,:destroy, :edit,:index, :show]

    resources :clients ,only: [:new, :create,:destroy, :edit] do
      resources :client_works ,only: [:new, :create,:destroy, :edit]
    end

    resources :users ,only: [:new, :create,:destroy, :edit] do
      resources :user_works ,only: [:new, :create,:destroy, :edit]
    end
resources :companies ,only: [:show, :edit,:update ]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
	belongs_to :company
	#belongs_to :daily_report
	has_many :client_works
end

app/models/client_work.rb
class ClientWork < ApplicationRecord
	belongs_to :client
	#belongs_to :daily_report
end

app/models/company.rb
class Company < ApplicationRecord
	has_many :clients
	has_many :users
end

app/models/daily_report.rb
class DailyReport < ApplicationRecord
	belongs_to :user
	has_many :expenses
	has_one :client
	has_one :client_work
end

app/models/expense.rb
class Expense < ApplicationRecord
	belongs_to :daily_report
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user_works
  belongs_to :company
  has_many :daily_reports
end

app/models/user_work.rb
class UserWork < ApplicationRecord
	belongs_to :user
	has_one :client_work
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
  	if current_user.admin == true
      root_path
    else
  		new_user_daily_report_path(current_user.id)
  	end
  end

  protected

	  def devise_parameter_sanitizer
	  	if resource_class == User
	  		User::ParameterSanitizer.new(User, :user, params)
	  	else
	  		super # Use the default one
	    end
	  end
end

app/controllers/client_works_controller.rb
class ClientWorksController < ApplicationController
  def new
    @client_work = ClientWork.new()
  end

  def create
    @client_work = ClientWork.create(client_work_params)
    @client_work.client_id = params[:client_id].to_i
    if @client_work.save
      redirect_to  client_path(id: @client_work.client_id)
    else
      redirect_to root_path
    end
  end

  def edit
  end

  def update
  end

  def delete
  end

  def show
  end

  def index

  end

  private

  def client_work_params
    params.require(:client_work).permit(:work_place,:work_name,:salary_per_man,:client_id)
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def new
    @client = Client.new()
  end

  def create
    @client = Client.new(client_params)
    @client.company_id = 1
    if @client.save
      redirect_to  new_client_client_work_path(client_id: @client.id)
    else
      redirect_to root_path
    end
  end

  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
  end

  def edit
  end

  def delete
  end

  private

  def client_params
    params.require(:client).permit(:client_name,:client_addr,:client_bill,:client_phone_number,:client_fax,:company_id)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def show
  	@company = Company.find(1)
  end

  def index
  end

  def edit
  end

  def update
  end
end

app/controllers/daily_reports_controller.rb
class DailyReportsController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @arr ||= []
    @user.user_works.each do |uw|
      @arr << uw.client_work_id
    end
    @daily_report = DailyReport.new()
    #binding.pry
  end

  def create
    @daily_report = DailyReport.create(daily_report_params)
    @daily_report.user_id = params[:user_id]
    @daily_report.work_date = work_date
    @daily_report.start_work_time = start_work_time
    @daily_report.finish_work_time = finish_work_time
    @daily_report.client_id =  ClientWork.find(params[:daily_report][:client_work_id].to_i).client.id
    if @daily_report.save
      redirect_to root_path
    else
      new_user_daily_report_path(current_user.id)
    end
  end

  def edit
  end

  def delete
  end

  def update
  end

  def show
  end

  def index
  end

  private

    def work_date
        year = params[:daily_report]['work_date(1i)']#年
        month = params[:daily_report]['work_date(2i)']#月
        day = params[:daily_report]['work_date(3i)']#日
        # hour = params[:daily_work]['eventtim(4i)']#時
        # min = params[:daily_work]['eventtime(5i)']#分
        #返り値
        Date.new(year.to_i, month.to_i, day.to_i)
    end

    def start_work_time
        year = params[:daily_report]['start_work_time(1i)']
        month = params[:daily_report]['start_work_time(2i)']
        day = params[:daily_report]['start_work_time(3i)']
        hour = params[:daily_report]['start_work_time(4i)']#時
        min = params[:daily_report]['start_work_time(5i)']#分
        DateTime.new(year.to_i,month.to_i,day.to_i,hour.to_i,min.to_i)
    end
    def finish_work_time
        year = params[:daily_report]['finish_work_time(1i)']
        month = params[:daily_report]['finish_work_time(2i)']
        day = params[:daily_report]['finish_work_time(3i)']
        hour = params[:daily_report]['finish_work_time(4i)']#時
        min = params[:daily_report]['finish_work_timi)']#分
        DateTime.new(year.to_i,month.to_i,day.to_i,hour.to_i, min.to_i)
    end

  def daily_report_params
    params.require(:daily_report).permit(:work_date,:client_id,:client_work_id,:start_work_time,:finish_work_time,:user_id)
  end
end

app/controllers/user_works_controller.rb
class UserWorksController < ApplicationController
  def new
    @user_work = UserWork.new()
    
  end

  def create
    @user_work = UserWork.create(user_work_params)
    @user_work.user_id = params[:user_id]
    if @user_work.save
      redirect_to root_path
    else
      new_user_user_work_path(user_id: params[:user_id])
    end

  end

  def edit
  end

  def delete
  end

  def index
  end

  def show
  end

  private

    def user_work_params
      params.require(:user_work).permit(:work_element,:work_salary,:work_overtime_salary,:user_id,:client_work_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
      respond_to do |format|
        format.html # show.html.erb
        format.pdf do
          pdf = UserPDF.new(@user)

          # 画面にPDFを表示する
          # disposition: "inline" によりPDFはダウンロードではなく画面に表示される
          send_data pdf.render,
            filename:    "#{@user.id}.pdf",
            type:        "application/pdf",
            disposition: "inline"
        end
      end
  end

  def new
  end

  def create
  end

  def edit
  end

  def delete
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_works_helper.rb
module ClientWorksHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/daily_reports_helper.rb
module DailyReportsHelper
end

app/helpers/user_works_helper.rb
module UserWorksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/client_works/create.html.erb
<h1>ClientWorks#create</h1>
<p>Find me in app/views/client_works/create.html.erb</p>

app/views/client_works/delete.html.erb
<h1>ClientWorks#delete</h1>
<p>Find me in app/views/client_works/delete.html.erb</p>

app/views/client_works/edit.html.erb
<h1>ClientWorks#edit</h1>
<p>Find me in app/views/client_works/edit.html.erb</p>

app/views/client_works/index.html.erb
<h1>ClientWorks#index</h1>
<p>Find me in app/views/client_works/index.html.erb</p>

app/views/client_works/new.html.erb
<h1><%= Client.find(params[:client_id]).client_name %>さんの現場追加</h1>
<%= form_for @client_work ,url:  client_client_works_path(client_id: params[:client_id]) do |f| %>

<div>
  <%= f.label :現場名 %>
  <%= f.text_field :work_place %>
</div>
<div>
  <%= f.label :作業名 %>
  <%= f.text_field :work_name %>
</div>
<div>
  <%= f.label :基本給 %>
  <%= f.text_field :salary_per_man %>
</div>

  <%=f.submit '次へ', class: 'btn btn-primary'%>
<% end %>

app/views/client_works/show.html.erb
<h1>ClientWorks#show</h1>
<p>Find me in app/views/client_works/show.html.erb</p>

app/views/client_works/update.html.erb
<h1>ClientWorks#update</h1>
<p>Find me in app/views/client_works/update.html.erb</p>

app/views/clients/create.html.erb
<h1>Clients#create</h1>
<p>Find me in app/views/clients/create.html.erb</p>

app/views/clients/delete.html.erb
<h1>Clients#delete</h1>
<p>Find me in app/views/clients/delete.html.erb</p>

app/views/clients/edit.html.erb
<h1>Clients#edit</h1>
<p>Find me in app/views/clients/edit.html.erb</p>

app/views/clients/index.html.erb
<h1> クライアント一覧 </h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th>客先名</th>
            <th>客先住所</th>
            <th>請求書送り先</th>
            <th>客先電話番号</th>
            <th>客先FAX</th>
        </tr>
    </thead>
    <tbody>
	<% @clients.each do |c| %>
        <tr>
            <th><%= c.client_name %></th>
            <td><%= c.client_addr %></td>
            <td><%= c.client_bill %></td>
            <td><%= c.client_phone_number %></td>
            <td><%= c.client_fax %></td>
            <td><%= link_to '編集',edit_client_path(c.id),method: :get,class: 'btn btn-primary' %>
           <%= link_to '削除',client_path(c.id),method: :delete ,class: 'btn btn-primary'%>
           <%= link_to '詳細',client_path(c.id),method: :get,class: 'btn btn-primary' %></td>
        </tr>
        <%end%>
    </tbody>
</table>

app/views/clients/new.html.erb
<%= form_for @client ,url: clients_path() do |f| %>

<div>
  <%= f.label :会社名 %>
  <%= f.text_field :client_name %>
</div>
<div>
  <%= f.label :住所 %>
  <%= f.text_field :client_addr %>
</div>
<div>
  <%= f.label :請求書送付先 %>
  <%= f.text_field :client_bill %>
</div>
 <div>
  <%= f.label :TEL %>
  <%= f.text_field :client_phone_number %>
</div>
<div>
  <%= f.label :FAX %>
  <%= f.text_field :client_fax %>
</div>

  <%=f.submit '次へ', class: 'btn btn-primary'%>
<% end %>

app/views/clients/show.html.erb
<%= @client.client_name %>
<% @client.client_works.each do |cw| %>
<div>
	<%= cw.work_place %>
	<%= cw.work_name %>
	<%= cw.salary_per_man %>
</div>
<% end %>

app/views/companies/edit.html.erb
<h1>Companies#edit</h1>
<p>Find me in app/views/companies/edit.html.erb</p>

app/views/companies/index.html.erb
<h1>Companies#index</h1>
<p>Find me in app/views/companies/index.html.erb</p>

app/views/companies/show.html.erb
<h1>Companies#show</h1>
<p>Find me in app/views/companies/show.html.erb</p>
<%= @company.company_name %>

<%= @company.company_addr %>
<%= @company.company_phone_number %>
<%= @company.company_fax %>
<%= @company.company_work_time %>
<%= @company.company_break_time %>
<%= @company.company_overtime_work %>
<%= @company.company_closing_date %>


<%= @company.company_bill %>

app/views/companies/update.html.erb
<h1>Companies#update</h1>
<p>Find me in app/views/companies/update.html.erb</p>

app/views/daily_reports/create.html.erb
<h1>DailyReports#create</h1>
<p>Find me in app/views/daily_reports/create.html.erb</p>

app/views/daily_reports/delete.html.erb
<h1>DailyReports#delete</h1>
<p>Find me in app/views/daily_reports/delete.html.erb</p>

app/views/daily_reports/edit.html.erb
<h1>DailyReports#edit</h1>
<p>Find me in app/views/daily_reports/edit.html.erb</p>

app/views/daily_reports/index.html.erb
<h1>DailyReports#index</h1>
<p>Find me in app/views/daily_reports/index.html.erb</p>

app/views/daily_reports/new.html.erb
<%#= 今日の日付は Date.today.year.to_s  年  Date.today.month.to_s 月 Date.today.day.to_s 日です。 %>

<h1>
  今日は
<%= Date.today.year.to_s %>
年
<%= Date.today.month.to_s %>
月
<%= Date.today.day.to_s %>
日
です
</h1>

<%= form_for @daily_report ,url: user_daily_reports_path(user_id: params[:user_id]) do |f| %>
<div>
	作業日
     <%= raw sprintf(
              f.date_select(
                  :work_date,
                  use_month_numbers: true,
                  start_year:        Time.now.year,
                  end_year:          (Time.now.year - 1),
                  #default:           Date.new(1989, 1, 1),
                  start_month: Time.now.year,
                  end_month:  Time.now.month,
                  defalut:           Time.now,
                  date_separator:    '%s'), # 年月日区切りをそれぞれ指定
              '年 ', '月 ') + '日'
   %>
</div>
<div>
  開始時刻
  <%= f.datetime_select :start_work_time, 
    use_month_numbers: true,
    defalut:   Time.now,
    minute_step: 10,
    discard_year: true
  %>
  〜
終了時刻
  <%= f.datetime_select :finish_work_time, 
    use_month_numbers: true,
    defalut:   Time.now,
    minute_step: 10,
    discard_year: true
  %>
</div>

<div>
  <% @arr.each do |arr| %>
  <% cw = ClientWork.find(arr) %>
  <%= f.radio_button :client_work_id, cw.id %>
  <%= Client.find(cw.client_id).client_name %>
  <%= f.label :client_work_id, cw.work_place, value: cw.id %>
  <%= cw.work_name %>
  <%end%>
</div>


  <%=f.submit '次へ', class: 'btn btn-primary'%>
<% end %>

app/views/daily_reports/show.html.erb
<h1>DailyReports#show</h1>
<p>Find me in app/views/daily_reports/show.html.erb</p>

app/views/daily_reports/update.html.erb
<h1>DailyReports#update</h1>
<p>Find me in app/views/daily_reports/update.html.erb</p>

app/views/user_works/create.html.erb
<h1>UserWorks#create</h1>
<p>Find me in app/views/user_works/create.html.erb</p>

app/views/user_works/delete.html.erb
<h1>UserWorks#delete</h1>
<p>Find me in app/views/user_works/delete.html.erb</p>

app/views/user_works/edit.html.erb
<h1>UserWorks#edit</h1>
<p>Find me in app/views/user_works/edit.html.erb</p>

app/views/user_works/index.html.erb
<h1>UserWorks#index</h1>
<p>Find me in app/views/user_works/index.html.erb</p>

app/views/user_works/new.html.erb
<%= form_for @user_work ,url: user_user_works_path(user_id: params[:user_id]) do |f| %>

<table class="table table-striped">
    <thead>
        <tr>
            <th>クライアント名</th>
            <th>現場</th>
        </tr>
    </thead>
    <tbody>
     <% Client.all.each do |client|%>
        <tr>
           <th><%= client.client_name %></th>
          <% client.client_works.each do |cw| %>
               <td> <%= f.radio_button :client_work_id, cw.id %>
            <%= f.label :client_work_id, cw.work_place, value: cw.id %>
            <%= cw.work_name %>
            </td>
            <% end %>
        </tr>
        <% end %>
    </tbody>
</table>


<div>
  <%= f.label :基本給 %>
  <%= f.text_field :work_salary %>
</div>

<div>
  <%= f.label :時間外労働 %>
  <%= f.text_field :work_overtime_salary %>
</div>
 
  <%=f.submit '次へ', class: 'btn btn-primary'%>
<% end %>

app/views/user_works/show.html.erb
<h1>UserWorks#show</h1>
<p>Find me in app/views/user_works/show.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>従業員一覧</h1>
<h1><%= link_to 'クライアント一覧',  clients_path, method: :get ,class: 'btn btn-primary btn-lg'%></h1>
<% if user_signed_in? && current_user.admin == true %>
	<%= link_to 'クライアントを追加する', new_client_path,class: 'btn btn-primary' %>
	<%= link_to '自社詳細へ' ,company_path(1), method: :get ,class: 'btn btn-primary'%>
<% end %>


<% if user_signed_in? %>
 <%= link_to 'ログアウト', destroy_user_session_path(user_id: current_user.id), method: :delete,class: 'btn btn-primary' %>
 <%else%>
  <%= link_to 'ログイン', new_user_session_path ,class: 'btn btn-primary' %>
<%end%>


<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>名前</th>
            <th>住所</th>
            <th>電話番号</th>
        </tr>
    </thead>
    <tbody>
	<% @users.each do |user| %>
        <tr>
            <th><%= user.id%></th>
            <td><%= user.name %></td>
            <td><%= user.address  %></td>
            <td><%= user.phone_number  %></td>
            <td><%= link_to '人工を追加する', new_user_user_work_path(user.id),class: 'btn btn-primary' %>
            <%= link_to '従業員詳細',  user_path(user.id),class: 'btn btn-primary' %>
            <%= link_to '作業日報を追加', new_user_daily_report_path(user.id),class: 'btn btn-primary' %></td>
        </tr>
        <%end%>
    </tbody>
</table>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= @user.name %>
<%= @user.address %>
<%= @user.phone_number %>
<%= @user.landline_phone_number %>

<% @user.daily_reports.each do |dr| %>
<div>
<%= dr.work_date %>
<%= Client.find(dr.client_id).client_name %>
<%= ClientWork.find(dr.client_work_id).work_place %>
</div>
<%end%>

<%= link_to "PDFで表示",
              user_path(@user, format: "pdf"),
              :class => 'btn btn-primary' %>